from .interp_mean import InterpMeanNet
from .interp_mean_prefix import InterpMeanPrefixNet
from .interp_inv_dist import InterpInvDistNet
from .interp_inv_dist_prefix import InterpInvDistPrefixNet
from .interp_max import InterpMaxNet
from .interp_attention import InterpAttentionNet
from .interp_attention_Kheads import InterpAttentionKHeadsNet